FROM openjdk:11-jre-slim

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    curl \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV SPARK_VERSION=3.4.1
RUN curl -L https://downloads.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz | tar xz -C /opt/
ENV SPARK_HOME=/opt/spark-${SPARK_VERSION}-bin-hadoop3
ENV PATH=$SPARK_HOME/bin:$PATH

RUN pip3 install pyspark numpy matplotlib pandas jupyter

WORKDIR /app

EXPOSE 4040 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.token=", "--NotebookApp.password="]
